export * from "./CardPokemon";
export * from "./Header";
export * from './PantallaInicial'
export * from './Error404'
export * from './Home'
export * from './Input'
export * from './Loading'
export * from './Search'
export * from './Select'